services:
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL://kafka:9094
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
  # kafka-ui:
  #   container_name: kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 8081:8080
  #   environment:
  #     DYNAMIC_CONFIG_ENABLED: true
  #     KAFKA_CLUSTERS_0_NAME: wizard_test
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092
  # payroll_mysql:
  #   image: mysql:5.6
  #   container_name: payroll_mysql
  #   cap_add:
  #     - SYS_NICE
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - mysqlseverdata:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # env_file:
      # - path: .env
        # required: false # default 
      # - path: .env.development
        # required: false
  # hr_sql:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: hr_sql
  #   cap_add:
  #     - SYS_NICE
  #   restart: always
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_SA_PASSWORD=@team1sys
  #   ports:
  #     - "1435:1433"
  #   volumes:
  #     - sqlserverdata:/var/opt/mssql
      # - mysql_volume:/var/lib/mysql
    # env_file:
volumes:
  mysqlseverdata:
  sqlserverdata: